---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/cert-manager/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: networking-cert-manager
  path: ./kubernetes/apps/networking/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m