---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-assistant-base
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/home-assistant/base
  dependsOn:
    - name: cloudnative-pg-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-age