apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: 6MOx8FJrrGtz7sAx
    AWS_SECRET_ACCESS_KEY: 459Rr3xJWVymF4NcN2sWoilBfcYf4U6Z
    AWS_ENDPOINTS: https://s3.lennart.cloud