apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.4.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      reclaimPolicy: Delete
    longhornUI:
      replicas: 1
    longhornConversionWebhook:
      replicas: 1
    longhornAdmissionWebhook:
      replicas: 1
    longhornRecoveryBackend:
      replicas: 1
    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.lennartbeneke.de
      tls: true
      tls-secret: lennartbeneke-de-tls-production
      path: /