---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rulezdzn@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-secret
    solvers:
      - dns01:
          cloudflare:
            email: rulezdzn@gmail.com
            apiKeySecretRef:
              name: cloudflare-secret
              key: api-key
        selector:
          dnsZones:
            - lennartbeneke.de
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rulezdzn@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-secret
    solvers:
      - dns01:
          cloudflare:
            email: rulezdzn@gmail.com
            apiTokenSecretRef:
              name: cloudflare-secret
              key: api-key
        selector:
          dnsZones:
            - lennartbeneke.de