---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gatus-base
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/gatus/base
  dependsOn:
    - name: cloudnative-pg-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m