apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster-default
  namespace: default
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 4Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-secret
  monitoring:
    enablePodMonitor: false