apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-secret
  postgresql:
    parameters:
      max_connections: '300'
  monitoring:
    enablePodMonitor: false