apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-repo
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 2
      extraEnvs:
        - name: TZ
          value: Europe/Berlin
      service:
        externalIPs: ["10.0.0.240"]
        externalTrafficPolicy: Local
      ingressClassResource:
        default: true
      allowSnippetAnnotations: true
      extraArgs:
        default-ssl-certificate: |-
          networking/lennartbeneke-de-tls-production
