---
- name: Set correct system timezone
  community.general.timezone:
    name: "{{ user_timezone }}"
- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - docker
- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    autoremove: true
- name: Install extra packages
  ansible.builtin.package:
    name: "{{ extra_packages }}"
    state: present
#- name: Uninstall snap
#  block:
#    - name: Remove snap packages
#      ansible.builtin.command: "snap remove --purge {{ item }} && touch ~/.snapdeleted"
#      loop:
#        - lxd
#        - core20
#        - snapd
#      args:
#        creates: '~/.snapdeleted'
#    - name: Uninstall snapd
#      ansible.builtin.apt:
#        name: snapd
#        state: absent
#        autoremove: true
