apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - bjw-s.yaml
  - cloudnative-pg.yaml
  - ingress-nginx.yaml
  - longhorn.yaml
  - metallb.yaml
  - uptime-kuma.yaml