---
apiVersion: v1
kind: Service
metadata:
  name: cnpg-authentik-lb
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs: ["10.0.0.241"]
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: cnpg-authentik
    role: primary