---
authentication_backend:
  file:
    path: /config/users.yaml
    watch: false
    search:
      email: true
      case_insensitive: true
    password:
      bcrypt:
        variant: standard
        cost: 12
session:
  redis:
    host: redis-master.default.svc.cluster.local
    port: 6379

access_control:
  default_policy: one_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: ["uptime.lennartbeneke.de"]
      resources: ["^/status.*$"]
      policy: bypass