---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lennartbeneke-de
  namespace: networking
spec:
  secretName: lennartbeneke-de-tls-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - '*.lennartbeneke.de'