---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lan-lennartbeneke-de
  namespace: networking
spec:
  secretName: lan-lennartbeneke-de-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - lennartbeneke.de
    - '*.lennartbeneke.de'