apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: networking
spec:
  addresses:
  - 10.0.0.240-10.0.0.249
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2-advertisement
  namespace: networking
spec:
  ipAddressPools:
  - metallb-ip-pool