apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: default
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5InXfHre8Ng/7ugRW1E=,iv:4Nb/ATYj50Y47Hn8uBLyXEd21ZZL7OjY51AQwrJwtCQ=,tag:uwc3yODX08lRjd1VDiVlkQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:IlY+j38AXiifZp9kVDa2UBTgfOE5mPyO0SosC+/Em5YzHvY4tw==,iv:JfGkfdMBj+qx+NY+XdTvG9x/McCSkL0MELGuDu/4/Vw=,tag:v+wsQz7hR8TBZQq61Yy4Tw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:nu6dbZFcXAgES2pze7Mgi4/ZI6ZOaNQuhQv2Ug==,iv:3YstDZd5J6LyYt1TPXzjDiZB0rTAEcVBTQ6idg6sos4=,tag:BqE6UmGPNdItbP2s7EDb9w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:tJvFuA==,iv:bl4V0WMfcs0Kdf7Yc1UIl3NaVDhDGy3t1sghaITidzY=,tag:KYNmpP/8dNzYhRZLJxPYRg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Ycj+NJwX/8LoKs83bQLZFq3mv8GWfApXzPXesw==,iv:RyaeIjS/4Dg2Ot9L2NVcpufvnxBfpbpdFu1Os/MIQ1I=,tag:D4qHwywvoqyxoGj7c/Hweg==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:U2xGJQ041YG5XE12y/aoeUXUcdz90wTZvxhJfdRBpcnIv2sxg1j6CnijbGvSweGa/Uc6Wpc+EjgI1rjYu6ACrG1KTH8PlV29AWml/v2pp+PoAdMLqWdGwjTWM81vBWEVpy5w,iv:TP+4C3+aYfso3YU3iYM8YJmw3oTqOYfzCyRMtR2PNFk=,tag:5Bu1m4sEUgKQxRrsd4CmLw==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:N+sPI37YaIpX,iv:X73ESpJrR8+gG8jfi5FSG360wLKvgWUnb1M29KmRjx0=,tag:UNdQufk2U2emwP8rjIyyzQ==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:UkvWHCL1J/I=,iv:oeXxjOVzWZORhiFzaaccDk5Voqc5WzyFFVq42mie5LY=,tag:pzJfgfsNh4MvFXRc7zH67w==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:JdM=,iv:fDIIVuQGOIs6ivkCd+yBPr4SxpT6UfQiCujhnCwZRfA=,tag:kBATVO8JRgyyC33lC/uYvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUWRKQlFQVlJvcmhtaTcy
            QTRWcEJCVWRNSHBvMXJUcGY4bVBsZWsrQlJRCnZTSkJzdEZsR3FUSWh6YkRLNUR3
            b0hSMlR6NldTZmMvTTdyczluWUh4dTAKLS0tIDJGbEhkUDJZTmlDZnJPL29iWk05
            NytJSDg1WmV1a041UG9SNFk4T05EUVUKIN+C9DvCN9jKocaZxMr86OgHWH4Cfvvq
            UwZYPqTWz09OX6yhCsPsIkCPNCQySsFXX4EGPnOp4DLW48xB8s+sxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T19:39:58Z"
    mac: ENC[AES256_GCM,data:YQjBoAxAl+dMfNAPvC6gX41oBO+g51xFYowGb576vILcj6rx78aQ3cDMvhpRzQ7USBzh0UcS3ZC/TrrAtdm48ZVLJUXKkRZQu6D2NFRoiv0BlsRLgKqR7QhqMVtRle4HclRX8BC6iwjktpamwRjsK3xFzTmZOgNQfXvNt2vN+tQ=,iv:kyio7HXafIc8WtNjoSUbeUSPaQLvk32ElWvBPrcuubQ=,tag:MO+l14nvWg35xlVa+zaT9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
