apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: default
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:NEuWxT0u+3x4JE5ZtSM=,iv:T3hYbzTDoKPTChqn5yR/+U9uDjCyCkQpDulV+NpCKSY=,tag:0ys1Ig4QwDTl2pYUm3hNrQ==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:61xZ7vVqE0joUvIhdiU1S+8hEAWyW8BEwA1lAdc+/r7XnjQx3g==,iv:oVDHbUWs8s544lHXpFFAPh2RylTY46iM7x5jd7YYhsE=,tag:ex5djlXElax8hh3NVKo2Aw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:so7gA+3nW3XSu/dpc9YW+pxjz0iM4hz43YiS5w==,iv:B1LL7RnhlrJwUhfdGCuDyrAFGN8W4iWESwAbu/P8vsw=,tag:AdvjYK/dzzpnzuawodOggQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hIOgLA==,iv:TtcfLMZrcMP3u/x49OdVpQ+1ep9igEmP4GawrADXqns=,tag:6pW1oxwNeZen+hnyiDFoRA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:cGEfHvPZX9syn0vLxH1PIYpXZqLD3wDr0f04kQ==,iv:PbrS2BpRCm1UBwAheFlb0QiFfk3w4kjCYdxYHGvjNQw=,tag:xTk8lMIkV9WkWYm8ILl/mQ==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:UDIHyKnuAAENHisp8KVWb6o+FfUEvbgbIAL5J0cXwvjgK3XHdgMP61bUm+RQssoUQaMzC3JOccjbYoMPJntH1rki1sBvOMs5/3Ri08paz5io9/D+dBeX53MhHDfSgVTZWw==,iv:8oXBlV1AbgcTWiZGVCNemfwoWTT1lNnKHAJp3s1G844=,tag:mwVpkiy0r70H1gX5SG+ZGQ==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:N+sPI37YaIpX,iv:X73ESpJrR8+gG8jfi5FSG360wLKvgWUnb1M29KmRjx0=,tag:UNdQufk2U2emwP8rjIyyzQ==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:UkvWHCL1J/I=,iv:oeXxjOVzWZORhiFzaaccDk5Voqc5WzyFFVq42mie5LY=,tag:pzJfgfsNh4MvFXRc7zH67w==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:uQsH+w==,iv:1UEis3lmqvqe+kH8GSS674Su7ADinsEuQFL4JDH0l14=,tag:IqfcrV/GtZjzt2JvvQTPOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUWRKQlFQVlJvcmhtaTcy
            QTRWcEJCVWRNSHBvMXJUcGY4bVBsZWsrQlJRCnZTSkJzdEZsR3FUSWh6YkRLNUR3
            b0hSMlR6NldTZmMvTTdyczluWUh4dTAKLS0tIDJGbEhkUDJZTmlDZnJPL29iWk05
            NytJSDg1WmV1a041UG9SNFk4T05EUVUKIN+C9DvCN9jKocaZxMr86OgHWH4Cfvvq
            UwZYPqTWz09OX6yhCsPsIkCPNCQySsFXX4EGPnOp4DLW48xB8s+sxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T18:42:19Z"
    mac: ENC[AES256_GCM,data:SSjy1ZHq53k5fO7hGxHujcHD2+dczpg1QTb2YBpWdAh3OibeTQF6SDmSy0HklHWsliw/gqHTt5+DG6dUW3Ki4TLe7Xx9fb/GTrtHjSDLVDr2XS1ir+k80KF1re0dCA+LG6PdAadGbCfo63hNHi7EZxfCBRGg2ziFsHtYHKCHIWs=,iv:XZi6b5qWeK/b73Zqib0Ti0WkTbzzOn64gGmQECeweO4=,tag:3+XXuJRAWKeeWDbsJBvlFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
