apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: default
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:NEuWxT0u+3x4JE5ZtSM=,iv:T3hYbzTDoKPTChqn5yR/+U9uDjCyCkQpDulV+NpCKSY=,tag:0ys1Ig4QwDTl2pYUm3hNrQ==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:61xZ7vVqE0joUvIhdiU1S+8hEAWyW8BEwA1lAdc+/r7XnjQx3g==,iv:oVDHbUWs8s544lHXpFFAPh2RylTY46iM7x5jd7YYhsE=,tag:ex5djlXElax8hh3NVKo2Aw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:so7gA+3nW3XSu/dpc9YW+pxjz0iM4hz43YiS5w==,iv:B1LL7RnhlrJwUhfdGCuDyrAFGN8W4iWESwAbu/P8vsw=,tag:AdvjYK/dzzpnzuawodOggQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hIOgLA==,iv:TtcfLMZrcMP3u/x49OdVpQ+1ep9igEmP4GawrADXqns=,tag:6pW1oxwNeZen+hnyiDFoRA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:iEpYv0lOqp8xo/eOyYSB/nBt2PIAiGEIgX7Nrw==,iv:OBN6rcdVS3h2xN99A1fCWJ45m9Be9VxYzQ91PgWfvSg=,tag:UXfO0o5DTBoh0FxSMTmKDQ==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:EQwCoAktBOZ9NfnZIVbZHQSI7LTtiJh92nqwFYl4mKiCDEAmeCHCYGHDlxlZZo818o2B8GoA0leg2UzkuJut9z6hRFAQGF+ryO8VdHqA8iE80HtBKcnu9eAZx5cGIf+/gQ==,iv:ZWAcfzECGqBGSOEFcFbQ28m2FHmF7N5l53lHpjFC4II=,tag:7Dwudd5/bbY0nue2TZu1tg==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:N+sPI37YaIpX,iv:X73ESpJrR8+gG8jfi5FSG360wLKvgWUnb1M29KmRjx0=,tag:UNdQufk2U2emwP8rjIyyzQ==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:UkvWHCL1J/I=,iv:oeXxjOVzWZORhiFzaaccDk5Voqc5WzyFFVq42mie5LY=,tag:pzJfgfsNh4MvFXRc7zH67w==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:uQsH+w==,iv:1UEis3lmqvqe+kH8GSS674Su7ADinsEuQFL4JDH0l14=,tag:IqfcrV/GtZjzt2JvvQTPOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUWRKQlFQVlJvcmhtaTcy
            QTRWcEJCVWRNSHBvMXJUcGY4bVBsZWsrQlJRCnZTSkJzdEZsR3FUSWh6YkRLNUR3
            b0hSMlR6NldTZmMvTTdyczluWUh4dTAKLS0tIDJGbEhkUDJZTmlDZnJPL29iWk05
            NytJSDg1WmV1a041UG9SNFk4T05EUVUKIN+C9DvCN9jKocaZxMr86OgHWH4Cfvvq
            UwZYPqTWz09OX6yhCsPsIkCPNCQySsFXX4EGPnOp4DLW48xB8s+sxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-01T19:30:59Z"
    mac: ENC[AES256_GCM,data:FVIwmEb5pxeb5OMmA9Um1I83zdH5t+M7kSbyyBfFxbgFIafQa5ckCeI/Ccy1tZ5XnC2PX96m+sah3mKU+O5vHKoR4u7fcyo/SXJ70o0T+aXQTgMg7wpZi5poo8wp7EKrHoYWgO1yuJvGVKS0r+qpbCe96Gsl7+9BzBdjhpx2q6I=,iv:jZqjvWkpSD6A7qS9OtBJau7EjCbLcv4V1B25oCle2mk=,tag:PqPgzuc7VtBj4zrfgkqZ1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
