apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: default
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:NEuWxT0u+3x4JE5ZtSM=,iv:T3hYbzTDoKPTChqn5yR/+U9uDjCyCkQpDulV+NpCKSY=,tag:0ys1Ig4QwDTl2pYUm3hNrQ==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:61xZ7vVqE0joUvIhdiU1S+8hEAWyW8BEwA1lAdc+/r7XnjQx3g==,iv:oVDHbUWs8s544lHXpFFAPh2RylTY46iM7x5jd7YYhsE=,tag:ex5djlXElax8hh3NVKo2Aw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:so7gA+3nW3XSu/dpc9YW+pxjz0iM4hz43YiS5w==,iv:B1LL7RnhlrJwUhfdGCuDyrAFGN8W4iWESwAbu/P8vsw=,tag:AdvjYK/dzzpnzuawodOggQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hIOgLA==,iv:TtcfLMZrcMP3u/x49OdVpQ+1ep9igEmP4GawrADXqns=,tag:6pW1oxwNeZen+hnyiDFoRA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:cGEfHvPZX9syn0vLxH1PIYpXZqLD3wDr0f04kQ==,iv:PbrS2BpRCm1UBwAheFlb0QiFfk3w4kjCYdxYHGvjNQw=,tag:xTk8lMIkV9WkWYm8ILl/mQ==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:UDIHyKnuAAENHisp8KVWb6o+FfUEvbgbIAL5J0cXwvjgK3XHdgMP61bUm+RQssoUQaMzC3JOccjbYoMPJntH1rki1sBvOMs5/3Ri08paz5io9/D+dBeX53MhHDfSgVTZWw==,iv:8oXBlV1AbgcTWiZGVCNemfwoWTT1lNnKHAJp3s1G844=,tag:mwVpkiy0r70H1gX5SG+ZGQ==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:h5ST1vyyLPa+,iv:daJE4qxS2jNO5/e80QAKtaz7PvqDsb5ndx83UuLVSyY=,tag:ynA9oVzPzN9+rX/EMzCqpQ==,type:float]
    HASS_LONGITUDE: ENC[AES256_GCM,data:jA8ztHdgovU=,iv:nTTTrBICbmAXAB7VmOJyHEEOc43QsaHO/gKyy0WceTI=,tag:XL84VjOYDI8uSfciuSbxXw==,type:float]
    HASS_ELEVATION: ENC[AES256_GCM,data:xyhmKg==,iv:Gch0YQ2pIm3epTj3v+Qa0EklV/YxsCZY5k2QuP71UaY=,tag:T1d9x6yC8NH69pioz3RnyQ==,type:float]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUWRKQlFQVlJvcmhtaTcy
            QTRWcEJCVWRNSHBvMXJUcGY4bVBsZWsrQlJRCnZTSkJzdEZsR3FUSWh6YkRLNUR3
            b0hSMlR6NldTZmMvTTdyczluWUh4dTAKLS0tIDJGbEhkUDJZTmlDZnJPL29iWk05
            NytJSDg1WmV1a041UG9SNFk4T05EUVUKIN+C9DvCN9jKocaZxMr86OgHWH4Cfvvq
            UwZYPqTWz09OX6yhCsPsIkCPNCQySsFXX4EGPnOp4DLW48xB8s+sxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T18:25:43Z"
    mac: ENC[AES256_GCM,data:9cdEDACetEXbR9g3vjw89U4iJsjux8tabIBaFZ2J7RftqgwRUi8MA0jWPMTemuj4PuLjNYnAdEC0V7n12rwiLu68pkEYmYEgG0WlwvOkRod0G2lBC+ozbWUSI3oXbk3eTDuq9L/Kh5NvwAtPc1FCZ+2xfDOC9v2Or+gZDHAfI4s=,iv:cBSqPXyccsN5J5my0sQ+BiTMwGOo4tsVC5i7Xiz95lU=,tag:yhtmFJIUnEzUIOZeEoIKZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
