apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: uptime-kuma
      version: 2.5.9
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma-repo
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    ingress:
      enabled: true
      hosts:
        - host: &host uptime.lennartbeneke.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: lennartbeneke-de-tls-production
          hosts:
            - *host
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.lennartbeneke.de?rm=$request_method
        nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/server-snippets: |
          location / {
            proxy_set_header Upgrade $http_upgrade;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_cache_bypass $http_upgrade;
          }
        hajimari.io/enable: 'true'
        hajimari.io/icon: 'simple-icons:uptimekuma'
        hajimari.io/appName: Uptime-Kuma
        hajimari.io/info: |
          Monitors uptime of services.
    volume:
      size: 4Gi
      storageClassName: longhorn