apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: uptime-kuma
      version: 2.5.7
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma-repo
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    ingress:
      enabled: true
      hosts:
        - host: uptime.lennartbeneke.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: lennartbeneke-de-tls-production
          hosts:
            - '*.lennartbeneke.de'
    volume:
      size: 4Gi
      storageClassName: longhorn