apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:/RbmHX3nhYh6EPw1jSj0a3q2kuaXwortqK3wnQ==,iv:BYsGqYqPfgIDl+Zto2gDcy3w9x0EjW+rAoa/p7A0WWA=,tag:EZk+f54W7IWgncZ6b9tqvg==,type:str]
    username: ENC[AES256_GCM,data:XLtemt7hTX4=,iv:FYkxxpN0HMW2TMrrICecmjZFmYLAhDZx6cwNP+1nnZ4=,tag:sK5NH68z64pOiIASY+mW1g==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:sCZEUf4xMCLL9glxWbl6T+MAXEY=,iv:tv6qnNHSy561cKhbj3CuOTpHLgk72PEXJH2s5q+Voxc=,tag:0COsiX3WwSfmhQoSDXEm0A==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:SFcfNuB3wt/ZXPzKZBePScZ6g7h+3h7aI83FrwkhY3Yr2eXgVW8nzg==,iv:RU7kD5yEQJUXrl1yxNqzgPvx6yHUIzCxsS6fi2cBFQY=,tag:kQ5SToi8iDD7riZhqel+1A==,type:str]
    aws-region: ENC[AES256_GCM,data:WRWU0Wq7defxkAur,iv:NgDAtPyeB0ACY/Hjm5/PjYoDdsoBCVntufV9D7pwTV0=,tag:rIs8rfKWVNmuIPGnmkGWyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVU9sVnh3M2tOcWp0Tzk0
            NDE3azNjeFpFNDZTRWl0dXdhY1lPR2lMR0VjCmVyUG5ZS01IdmxiK2gyUVRWZzdk
            SVczRVV0T1o5VURPL3JWTFR3bWlsMk0KLS0tIHVHTUZNdHdsblFYTUVYV3krNnJt
            K1J5bjBpV0ZUNHlmSlRBV2lwUXRmOVEKIqyaG+sb5h1M38vmPq3Ja00d2uT3XohG
            WVp0vnNZ1Wc+KPJ78vL99xvXaRRQrefhFBNl0dDl2SSAa7ep/+Ol6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T16:17:20Z"
    mac: ENC[AES256_GCM,data:R0bPQmP997TzztGOy2wvADECyeNx9pwt5KchI4aRnKO6zF+Bm2XnFSSRHKDFfG4QEqEqUE4IntQWAhfAU/YQYDWhDel8p+8BS/YXo1C8IY++m4XjUS+Je/A8tVNCWVHSP9dFty6QbLDjcwRjYREEfKeYqYvc8ZHbJzQhCZyDFWI=,iv:flEc0FH+HKtvjmZ3viYiUkLFy+35lPSzI69IIRT42CQ=,tag:szZWyb9c4h78c4DIIS4+9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
