---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-base
  namespace: flux-system
spec:
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: redis-base
  path: ./kubernetes/apps/default/authelia/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-age