apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: vaultwarden-pg-secret
data:
    username: ENC[AES256_GCM,data:xltGuVoVGqXhMeQ=,iv:JXCAgt7xogvzc3JqKrbcFpPdnDl66bHXIv+vccbSWaA=,tag:Q/E4YQkq8ovwhr66KdIE0A==,type:str]
    password: ENC[AES256_GCM,data:6qFkoM2T4v4N2hpLE0TEhm/DQGyqnKZDR4kGsQ==,iv:tPmxe4AZ5Ve1snII8/13usBZmF92cOTH3D5hmYApNrk=,tag:RA7ccI6Yx8MlPw3oc0bx3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ3gxVkhKZ0VLN0tydkdx
            VHY0eE83SmxONi9ONWdmVVBQSlUxdjBZQ0Q4CnpnNTlyc0NxcmZGMlluR2t4WStI
            ZEVjNFpsQTRiVmdLZmdmSU5pTHZhQ3MKLS0tIGdwdnA1WG42YmtUK1FZR0p1WE9w
            VWlra1lRYTlIMG15WmxXR3Y4L3JsbzAKPAJRyo4ppKfZMurT46Ho4xd+Q/0zLktC
            5bbR3UhIDB2yVg/l1OEVBoNoP9Wi5Tbm9Y5R7p5RgegxB1GwXqvLYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T19:37:33Z"
    mac: ENC[AES256_GCM,data:m8P8yK/DuZWmLxnmsfMxyr5PKq78ARJUyER0uQslgcqEfYAPTAIjLtJhPl6+4XzXlvDDJ8q9XfI59TW8FaUSsK9LJBbmkD7i7m5GtaV8ii4M0beYqVI+KDQTsxmSGDjOw8MT0w5i4hSHGvjbmtrQV4xNvVVa/IH3N/321b59Dac=,iv:CXxp9HJewofZ9W5vlC5iLyZJ1ADQDBWWxiqIR5Gg0s4=,tag:3UNXZM6vangcYyCFd3b+CA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
