apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
metadata:
    name: vaultwarden-pg-superuser-secret
stringData:
    username: ENC[AES256_GCM,data:rtlIF0DDEeg=,iv:BJ+5/wJ6QZHpvyIIalfm8d8qOe9GUpIE0wuBZYSbuLc=,tag:9Gc4lInUopCDzj5m+piMfQ==,type:str]
    password: ENC[AES256_GCM,data:nQ7nu9xj95GpwxSKS5gGru/QSr8vOA+A38fiCg==,iv:UZd9/EQRr+k1JznEccnuSrjIR3ARhDOPyCWcD3Sz29w=,tag:fDYoL3tlC2Qu1gmy0/lM7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSUxmMkpJK21KWU8xenhS
            MUZ2L1dPVm5ycGdyazZCMVQ2ZVozcDBhbWswCjZ0K1JYWStIV0V6ckcyWTBoK2Nw
            NjlXMCtqTHJ2WkJ2bkN5SXZRdmxwajQKLS0tIEpLOXA3RFVQMFhxSS9ub2xXOVZn
            YytDYzhvSEF2SkxsUzNVRzAxOG1QbkUKODZlLVfAv+IRZd9HDKdSfrtHHdFd7tNF
            ku0mDJtlN/LJ4LwKXbUoaCR6QbdhI/+HEsnHsBUiphhSsWOJbf3prA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T20:21:00Z"
    mac: ENC[AES256_GCM,data:XEVyZKs3j+Le/TI1eGITqcC5yBNnMrMnunlqInkiZ0a+ZldG9avzJAFljd/Lppp8MH+TZ4K81p3u+oxlXQUkKajpNgslk7qBaPMYGXYWC+9Y+LZfBt4GQpH2nhmopAVmtRwjD5m7H379iM1gSIRz01w/l/WyfTVYBFb0lS4Ap5s=,iv:Ez0rMu+fdmhK52EznmA4mzM38OlbcLjHlebI4E8uRqk=,tag:V1XUyzW5HHs4livULdbYTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
