apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: default
stringData:
    pg-password: ENC[AES256_GCM,data:qPihafLF2KbSw9dmhHKNG8LIUNML6RaimZoPzQ==,iv:yhIoN7/eTF96N7rfJNu0W3Z+qRjGZg2XLVxQOHfWa+o=,tag:Y30QKejSj7ZI29yZYWqbCQ==,type:str]
    pg-user: ENC[AES256_GCM,data:mcWaQotLzQ==,iv:sC56/nEEvzSowBzZu60YcK5HfLCypOucrg0f0MdbI7w=,tag:VQTf5dsGOQYyIca5rdL1kw==,type:str]
    secret-key: ENC[AES256_GCM,data:cKCBGuvxPvBIVT8F7tU3PiG9ShenUMwULiO/LnkM3fZoWUTPMHeAXaAky4uJqhr6,iv:wsvPvIdZZe9Hzifhx8oQZ8PohYwhulWP8nWQWNd7LRA=,tag:hx3F7M414LqakZXTfXks6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa1pEdE42L3dnTUJ5Q21a
            dUphNzFsNW9sbjNnNmIyYXBsMk9QdEQxb0FzCnYyMnVMazcreGg1L3d1QmpqTWlW
            Z1hxcmxNWHp3a3pVb2V3WTJBMnRxWk0KLS0tIG9rOU5rUEpScitTamN1Z3BpVXF3
            ai9LOEFvWGtTaE9DNEgyT0lBbXZvQVEKljATf+UIPXTXCaFYlLE7OqbAt3llYL8J
            FGB5vS1H/S14UFS5lZfj6uYmzq7JEdPEueMG3Dzft6l5zhYu+bsDZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-14T16:23:56Z"
    mac: ENC[AES256_GCM,data:PQDjHkC4OqVbDR1JsanNjUgorIFx6CsYVsOqy0+p8/lc9IDJDu9YGnY6iAZBV8oy0P1ejE0GAdPgh5amr7aNOfJEaCVdsU8BAQJPjyM1kKhoAhm9x9nSzHzQXBmkFB4fjVAaSG8JVb38ABR+GOmULOZVa18+/2XtaFjGW6ZvzYM=,iv:OIziun9xuXTIyf7cLdJP9zWwYnAMMYusQSIDqB+H3zg=,tag:CDfosHvUpqvIKkWkDu5Ilg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
