apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgres
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:+Yd65ooz7afEorUVt+K82GPR2bE/o5lztCdQow==,iv:tUfc75yVSj+8EhDbvS0s9BfJfOorDIS0RIkbq/OGKkM=,tag:nkxlduC3kr8Y1EMN2me8vw==,type:str]
    user: ENC[AES256_GCM,data:DhPI25leyg==,iv:JuIBAcKmktlEfjc/iR+ZJwjNh4K58srlH20bu7XxVV4=,tag:+CRZwsbnVKd6iMautqc5mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa1pEdE42L3dnTUJ5Q21a
            dUphNzFsNW9sbjNnNmIyYXBsMk9QdEQxb0FzCnYyMnVMazcreGg1L3d1QmpqTWlW
            Z1hxcmxNWHp3a3pVb2V3WTJBMnRxWk0KLS0tIG9rOU5rUEpScitTamN1Z3BpVXF3
            ai9LOEFvWGtTaE9DNEgyT0lBbXZvQVEKljATf+UIPXTXCaFYlLE7OqbAt3llYL8J
            FGB5vS1H/S14UFS5lZfj6uYmzq7JEdPEueMG3Dzft6l5zhYu+bsDZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-14T15:32:19Z"
    mac: ENC[AES256_GCM,data:gp1eEM7c5S6uOw6yELw0UtMI6sWCrm8zGdqXAnRdEiHCxyxQYlxDBcmsKM3I9rdotcpIRC51KNHKYm3jo70O6SZYPKLMqqF13I+8A9Fhx8kSR8V1kzyG1t1OhZZeCkLVNP4AEQXVXbaBq3zMi1K6Z2+xgA7zFuzbAj06Sz+KOn4=,iv:IDD/JHsL3vkmcKCj1JFGjsQ69PIj5pdDercEFPvpCmI=,tag:V7uYKLtUO4R79tTxd0aByg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
