apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.2.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.7
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: authentik-secret
    authentik:
      redis:
        host: redis-master.default.svc.cluster.local
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: auth.lennartbeneke.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: lennartbeneke-de-tls-production
          hosts:
            - '*.lennartbeneke.de'
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secret
      valuesKey: POSTGRES_USER
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-secret
      valuesKey: POSTGRES_PASS
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secret
      valuesKey: POSTGRES_HOST
      targetPath: authentik.postgresql.host
    - kind: Secret
      name: authentik-secret
      valuesKey: POSTGRES_DB
      targetPath: authentik.postgresql.name