apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    authentik:
      postgresql:
        host: cnpg-authentik-rw.default.svc.cluster.local
        name: authentik
      redis:
        host: redis-master.default.svc.cluster.local
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: auth.lennartbeneke.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: lennartbeneke-de-tls-production
          hosts:
            - '*.lennartbeneke.de'
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: secret-key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secret
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: authentik-secret
      valuesKey: password
      targetPath: authentik.postgresql.password