- name: Ensure k3s directory exists
  file:
    path: '{{ k3s_path }}'
    state: directory
- name: Copy k3s config file to host
  template:
    src: 'k3s_config.yaml.j2'
    dest: '{{ k3s_path }}/config.yaml'
- name: Join cluster
  vars:
    token: '{{ lookup("file", "token") }}'
    clusterIP: '{{ hostvars[groups["master"][0]]["ansible_default_ipv4"]["address"] }}'
  block:
    - name: Install k3s and connect to new cluster
      environment:
        K3S_TOKEN: '{{ token }}'
        K3S_URL: 'https://{{ clusterIP }}:6443'
      shell: 'curl -sfL https://get.k3s.io | sh -s - server --disable traefik --disable servicelb'