apiVersion: batch/v1
kind: CronJob
metadata:
  name: vaultwarden-scheduled-backup
  namespace: default
spec:
  schedule: '0 4 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup-s3
            image: eeshugerman/postgres-backup-s3:16@sha256:cfcaa57732c13d0724312a2eea1ad3e385f5ed049de3c626d1ef28ecc13cdddb
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: vaultwarden-secret
          restartPolicy: OnFailure