apiVersion: batch/v1
kind: CronJob
metadata:
  name: vaultwarden-scheduled-backup
  namespace: default
spec:
  schedule: '0 4 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup-s3
            image: eeshugerman/postgres-backup-s3:15@sha256:c55817c5e84547ff13ea66a01a3788a30ae502f0f09e67736f768db6f794b312
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: vaultwarden-secret
          restartPolicy: OnFailure