---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-repo
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: vaultwarden/server
      tag: 1.29.2-alpine
    envFrom:
      - secretRef:
          name: vaultwarden-secret
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: &port 80
          websocket:
            enabled: true
            port: 3012
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /alive
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    serviceMonitor:
      main:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'simple-icons:bitwarden'
          hajimari.io/appName: Vaultwarden
          hajimari.io/info: Passwordmanager
        hosts:
          - host: &host vault.lennartbeneke.de
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /notifications/hub/negotiate
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      data:
        enabled: true
        existingClaim: vaultwarden-pvc
        mountPath: /data
    resources:
      limits:
        memory: 300Mi
        cpu: 200m