apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden-restore
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: postgres-backup-s3
        image: eeshugerman/postgres-backup-s3:15@sha256:c55817c5e84547ff13ea66a01a3788a30ae502f0f09e67736f768db6f794b312
        imagePullPolicy: IfNotPresent
        command: ['sh', 'restore.sh', '2023-08-29T02:00:01'] # change timestamp to restore correct backup
        envFrom:
          - secretRef:
              name: vaultwarden-secret
      restartPolicy: OnFailure