apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: default
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:OpUHCIQWqcVwNWC/kpkp27wVeCMOVwrWoi+JgAt4tudTyfBrijmQi5m0Hr+4FeLuuaaRzv4feA2+LF00qG5ZtvMyecB2EfuRe4dyC4tDnY0W2qSDv5GwhBZDQpIixS9pATFSdRlUrwH4dDUxkg==,iv:Xl4zCztkF2NRcjo7C/OSU9vKTZ4MJ0uXRHrkUNGCzZs=,tag:NBWQbJgq9dNZi/a7cRuvsQ==,type:str]
    WEBSOCKET_ENABLED: ENC[AES256_GCM,data:1TBzcQ==,iv:W3uy3WkLSdGR3Da7bSjvh39S/NFi9vXIyNMgMQW/PEU=,tag:cRLvIZTeJZAwGdyP4DaFJA==,type:str]
    DOMAIN: ENC[AES256_GCM,data:XMqlQPFff+bR7NP3M4arKqVqo8dMczQ1fHVJgAyE,iv:ldmj9EPLMc6j0q8zk5VXb07uz7/dJneCiZBWb+1VG74=,tag:Kwz2+wf59gPqh1RsJ2qHhQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:jPSbuBJ87a9Jsxa+TFw=,iv:yN5yMAyl5UU8k+oTZ0Ok4oZQ+/bxnAhriIircP9f4EE=,tag:BIYMc1J5OIMorHHyO5jyQw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:HvtRf1rCAIZnnPMWFcO1jz1+,iv:nfasM+AfBlHGSrE1Zan77zws0koBiarUVdaE1S5sf44=,tag:2B478S15rX1MkuaLh6BUQg==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:Y4eLU2sVv+7uBqg=,iv:iVXqBiAyG/tngBMgLgsHuTHuq9nixq8trb8v8L+zf1o=,tag:qmXhKyPQBgT19bjfV8P7Kw==,type:str]
    SMTP_SECURITY: ENC[AES256_GCM,data:Q+ZUmnmBDGXm,iv:vqPyGWQUhpIlsBtCxss6MKzO9Czj5cBxPny9B0vqv+8=,tag:6uuK1PR+VjeqB0c+lEHacQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:3WOY,iv:hTcda3GsUQnnvsNIpiY6VX4ruciENrWvA2z6ds5DzS8=,tag:AHcWJ2Tc5BspxFd9YVJwPQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:waIii2RhZlYBdAbCdxTSDWfX,iv:c7H2eutfmW4DLyPiT0EhDpbdnLZquWPX4i9RhfMuQjU=,tag:0f1k+qGXiPabOIlb969ScA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:4/r2/vqaWUbT4DqsRQl3DjYZvIc=,iv:mOZCCQd5brjK1800fHoGlRFJIzAE/aShN3sKXSN17cE=,tag:BP7dLC7y7bjDxtU87Mhtjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e2sfwa84lw80w9m3ap8naamgudu7wyrm5xn4l5ll3te84l2xs3fqe2zmue
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbDR2MlcwMk1kcEV6OTdT
            dmc2RHJKcGJCbHRiVzh3a3NwbGJidlVKM3drCjQ2TlFIWGRpSXMvN3VGQVo1T3FT
            RCtLcEF4dVdVWkZTZzJYVHdRNWVCTWMKLS0tIFVKbkhCL1dEK1dDQ1JoR285RFow
            SDNSbFpCWHhVUWZpdFVnYWVRa21QVTAKMcyDFN5p8Dzb/xb+aob1YN02/bQbhLLT
            2xUgjyY+CrZGJOEfZiSIdnfrBraTJfJwFuQntSZzu/l5VxjWxdYyrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T20:30:05Z"
    mac: ENC[AES256_GCM,data:MKjZn5+Z/NYQC54jo+qKsfGoNKYCBGzXTHiQFa4EmyX6f5jqgw3H4W5TVVqQcW58cxJvIab240oiTNlCc07gEeRXyWJLPaA/isPXbR0MvFEA75lSt/fqX4jZp4kSkDRgtBYF26sH5WIiNPwJEJ/2O3HkcZFeZwmVACwaHv1OVxQ=,iv:TCX5VBDcKRJ0tl7QEE8f4RFhyMNpJ2AHPhCEg3ZbOc0=,tag:LgiAxyX2635o7Ucej4V/rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.7.3
